version: "3.8"
services:
  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_AUTH_PASS}
      MARIADB_DATABASE: ${DB_AUTH_DATABASE}
      MARIADB_USER: ${DB_AUTH_USER}
      MARIADB_PASSWORD: ${DB_AUTH_USER_PASS}
    restart: ${RESTART}
    volumes:
      - ./mariaDB/data:/var/lib/mysql:rw
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.0
    command: start
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # DB
      KC_DB: mariadb
      KC_DB_USERNAME: ${DB_AUTH_USER}
      KC_DB_PASSWORD: ${DB_AUTH_USER_PASS}
      KC_DB_URL_HOST: mariadb
      KC_DB_URL_PORT: 3306
      KC_DB_URL_DATABASE: ${DB_AUTH_DATABASE}
      # (optionnel) pool plus tolérant au démarrage
      # KC_DB_POOL_INITIAL_SIZE: 1
      # KC_DB_POOL_MIN_SIZE: 1
      # KC_DB_POOL_MAX_SIZE: 10
      KC_PROXY: edge
      KC_HOSTNAME_URL: https://keycloak.lucette-pomponette.fr
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - app-network
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_MAIN_PORT}:5672"
      - "${RABBITMQ_UI_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    networks:
      - app-network

  backend_clients:
    build: ./app/clients
    ports:
      - "32783:3000"
    volumes:
      - ${LOGS_FOLDER}:/logs
    restart: ${RESTART}
    environment:
      # Rabbit
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_MAIN_PORT}
      RABBITMQ_QUEUE: ${RABBITMQ_QUEUE_CLIENTS}
      NODE_ENV: ${NODE_ENV}
      # DB (mock data DB)
      DB_USER: ${CLIENTS_DB_USER}
      DB_PASS: ${CLIENTS_DB_PASS}
      DB_NAME: ${MARIADB_MOCK_DATABASE}
      # MISCELLANEOUS
      LOGS_FOLDER: /logs
      LOG_LEVEL: ${LOG_LEVEL}
    depends_on:
      - db_mock_data
      - rabbitmq
    networks:
      - app-network

  backend_orders:
    build: ./app/orders
    volumes:
      - ${LOGS_FOLDER}:/logs
    restart: ${RESTART}
    environment:
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_MAIN_PORT}
      RABBITMQ_QUEUE: ${RABBITMQ_QUEUE_ORDERS}
      NODE_ENV: ${NODE_ENV}
      DB_USER: ${ORDERS_DB_USER}
      DB_PASS: ${ORDERS_DB_PASS}
    depends_on:
      - rabbitmq
    networks:
      - app-network

  backend_product:
    build: ./app/product
    volumes:
      - ${LOGS_FOLDER}:/logs
    restart: ${RESTART}
    environment:
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_MAIN_PORT}
      RABBITMQ_QUEUE: ${RABBITMQ_QUEUE_PRODUCTS}
      NODE_ENV: ${NODE_ENV}
      DB_USER: ${PRODUCTS_DB_USER}
      DB_PASS: ${PRODUCTS_DB_PASS}
    depends_on:
      - rabbitmq
    networks:
      - app-network

  db_mock_data:
    image: mariadb:latest
    restart: ${RESTART}
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_MOCK_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_MOCK_DATABASE}
      MARIADB_USER: ${MARIADB_MOCK_USER}
      MARIADB_PASSWORD: ${MARIADB_MOCK_PASSWORD}
    volumes:
      - ./mock_mariaDB/data:/var/lib/mysql:rw
      - ./mock_mariaDB/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "${MARIADB_MOCK_EXPOSE_PORT}:3306"
    networks:
      - app-network

  db_mock_import:
    build: mockDataImport
    container_name: mockapi-importer
    profiles:
      - importer
    restart: "no"
    environment:
      DB_HOST: db_mock_data
      DB_PORT: 3306
      DB_NAME: ${MARIADB_MOCK_DATABASE}
      DB_USER: ${MARIADB_MOCK_USER}
      DB_PASSWORD: ${MARIADB_MOCK_PASSWORD}
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - app-network
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASS}
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - app-network
    ports:
      - "3001:3000"
networks:
  app-network:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data:
