version: "3.8"
services:

  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASS}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
    restart: unless-stopped
    volumes:
      - ./mariaDB/data:/var/lib/mysql:rw
    networks:
      - app-network

  backend_clients:
    build: ./app/clients
    volumes:
      - ./logs:/logs
    depends_on:
      - db
    restart: ${RESTART}
    links:
      - db
    networks:
      - app-network

  backend_orders:
    build: ./app/orders
    volumes:
      - ./logs:/logs
    depends_on:
      - db
    restart: ${RESTART}
    links:
      - db
    networks:
      - app-network

  backend_product:
    build: ./app/product
    volumes:
      - ./logs:/logs
    depends_on:
      - db
    restart: ${RESTART}
    links:
      - db
    networks:
      - app-network


networks:
  app-network:
    driver: bridge



