version: "3.8"
services:

  db_auth:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_AUTH_PASS}
      MARIADB_DATABASE: ${DB_AUTH_DATABASE}
      MARIADB_USER: ${DB_AUTH_USER}
      MARIADB_PASSWORD: ${DB_AUTH_USER_PASS}
    restart: ${RESTART}
    volumes:
      - ./mariaDB/data:/var/lib/mysql:rw
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_MAIN_PORT}:5672"
      - "${RABBITMQ_UI_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    networks:
      - app-network

  backend_clients:
    build: ./app/clients
    volumes:
      - ./logs:/logs
    restart: ${RESTART}
    environment:
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_MAIN_PORT}
      RABBITMQ_QUEUE: ${RABBITMQ_QUEUE_CLIENTS}
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - rabbitmq
    networks:
      - app-network

  backend_orders:
    build: ./app/orders
    volumes:
      - ./logs:/logs
    restart: ${RESTART}
    environment:
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_MAIN_PORT}
      RABBITMQ_QUEUE: ${RABBITMQ_QUEUE_ORDERS}
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - rabbitmq
    networks:
      - app-network

  backend_product:
    build: ./app/product
    volumes:
      - ./logs:/logs
    restart: ${RESTART}
    environment:
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_MAIN_PORT}
      RABBITMQ_QUEUE: ${RABBITMQ_QUEUE_PRODUCTS}
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - rabbitmq
    networks:
      - app-network

networks:
  app-network:
    driver: bridge