services:

  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: keycloak
      MARIADB_USER: keycloak
      MARIADB_PASSWORD: keycloakpass
    restart: unless-stopped
    volumes:
      - './mariaDB/data:/var/lib/mysql:rw'
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.0
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # db
      KC_DB: mariadb
      KC_DB_SCHEMA: keycloak
      # KC_DB_URL: jdbc:mariadb://db_auth:3306/keycloak
      # KC_DB_URL: jdbc:mariadb://mariadb:3306/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloakpass
      # KC_HOSTNAME_STRICT: "false"
      # KC_HTTP_ENABLED: "true"
      KC_DB_URL_HOST: mariadb
    volumes:
      - './themes:/opt/keycloak/themes'
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - app-network

  backend_clients:
    build: ./app/clients
    volumes:
      - ./logs:/logs
    restart: ${RESTART}
    networks:
      - app-network

  backend_orders:
    build: ./app/orders
    volumes:
      - ./logs:/logs
    restart: ${RESTART}
    networks:
      - app-network

  backend_product:
    build: ./app/product
    volumes:
      - ./logs:/logs
    restart: ${RESTART}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge