version: "3.8"
services:

  db_auth:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_AUTH_PASS}
      MARIADB_DATABASE: ${DB_AUTH_DATABASE}
      MARIADB_USER: ${DB_AUTH_USER}
      MARIADB_PASSWORD: ${DB_AUTH_USER_PASS}
    restart: ${RESTART}
    volumes:
      - ./mariaDB/data:/var/lib/mysql:rw
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_MAIN_PORT}:5672"
      - "${RABBITMQ_UI_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    networks:
      - app-network

  backend_clients:
    build: ./app/clients
    volumes:
      - ./logs:/logs
    restart: ${RESTART}
    environment:
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_MAIN_PORT}
      RABBITMQ_QUEUE: ${RABBITMQ_QUEUE_CLIENTS}
      NODE_ENV: ${NODE_ENV}
      DB_USER: ${CLIENTS_DB_USER}
      DB_PASS: ${CLIENTS_DB_PASS}
    depends_on:
      - rabbitmq
    networks:
      - app-network

  backend_orders:
    build: ./app/orders
    volumes:
      - ./logs:/logs
    restart: ${RESTART}
    environment:
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_MAIN_PORT}
      RABBITMQ_QUEUE: ${RABBITMQ_QUEUE_ORDERS}
      NODE_ENV: ${NODE_ENV}
      DB_USER: ${ORDERS_DB_USER}
      DB_PASS: ${ORDERS_DB_PASS}
    depends_on:
      - rabbitmq
    networks:
      - app-network

  backend_product:
    build: ./app/product
    volumes:
      - ./logs:/logs
    restart: ${RESTART}
    environment:
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_MAIN_PORT}
      RABBITMQ_QUEUE: ${RABBITMQ_QUEUE_PRODUCTS}
      NODE_ENV: ${NODE_ENV}
      DB_USER: ${PRODUCTS_DB_USER}
      DB_PASS: ${PRODUCTS_DB_PASS}
    depends_on:
      - rabbitmq
    networks:
      - app-network

  db_mock_data:
    image: mariadb:latest
    restart: ${RESTART}
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_MOCK_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_MOCK_DATABASE}
      MARIADB_USER: ${MARIADB_MOCK_USER}
      MARIADB_PASSWORD: ${MARIADB_MOCK_PASSWORD}
    volumes:
      - ./mock_mariaDB/data:/var/lib/mysql:rw
      - ./mock_mariaDB/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "${MARIADB_MOCK_EXPOSE_PORT}:3306"
    networks:
      - app-network

  db_mock_import:
    build: mockDataImport
    container_name: mockapi-importer
    profiles:
      - importer
    restart: "no"
    environment:
      DB_HOST: db_mock_data
      DB_PORT: 3306
      DB_NAME: ${MARIADB_MOCK_DATABASE}
      DB_USER: ${MARIADB_MOCK_USER}
      DB_PASSWORD: ${MARIADB_MOCK_PASSWORD}
    networks:
      - app-network


networks:
  app-network:
    driver: bridge