global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "clients"
    metrics_path: /metrics
    static_configs:
      - targets: ["backend_clients:3000"]
        labels: { service: clients }

  - job_name: "orders"
    metrics_path: /metrics
    static_configs:
      - targets: ["backend_orders:3000"]
        labels: { service: orders }

  - job_name: "products"
    metrics_path: /metrics
    static_configs:
      - targets: ["backend_product:3000"]
        labels: { service: products }

  - job_name: "keycloak"
    metrics_path: /metrics
    static_configs:
      - targets: ["keycloak:8080"]
        labels: { service: keycloak }
