name: tests Jest for all API

on:
  workflow_dispatch:
  push:
    branches: [develop, main]
  pull_request:

permissions:
  contents: read

jobs:
  jest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        api:
          - { name: clients,  path: app/clients }
          - { name: orders,   path: app/orders }
          - { name: products, path: app/product }
    steps:
      # Submodules avec pat
      - name: Checkout (root + submodules)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.GH_SUBMODULES_TOKEN }}

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ${{ matrix.api.path }}/package-lock.json

      - name: Install deps
        working-directory: ${{ matrix.api.path }}
        run: npm ci

      - name: Run Jest (with coverage)
        env:
          NODE_ENV: test
        working-directory: ${{ matrix.api.path }}
        run: npm test -- --ci --coverage

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.api.name }}
          path: ${{ matrix.api.path }}/coverage
